# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  PracticeProject_config = debug

else ifeq ($(config),release)
  PracticeProject_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := PracticeProject

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PracticeProject:
ifneq (,$(PracticeProject_config))
	@echo "==== Building PracticeProject ($(PracticeProject_config)) ===="
	@${MAKE} --no-print-directory -C PracticeProject -f Makefile config=$(PracticeProject_config)
endif

clean:
	@${MAKE} --no-print-directory -C PracticeProject -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PracticeProject"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"